version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: git-logs-server
    environment:
      POSTGRES_DB: git-logs-server
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: